name: "CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: npm --frozen-lockfile

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: npm i --frozen-lockfile

      - name: "Build"
        run: npm run build

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: npm i --frozen-lockfile

      - name: "Test"
        run: yarn test:coverage --testLocationInResults --reporters=default --reporters=@jamesacarr/jest-reporter-github-actions

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true

  dependabot-merge:
    name: "Dependabot automerge"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    needs: [ "test", "build", "lint" ]
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: 'minor'

  semantic-release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [ "test", "build", "lint" ]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: npm i --frozen-lockfile

      - name: "Build package"
        run: npm run build

      - name: "Release"
        id: "release"
        uses: codfish/semantic-release-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}